version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/library

  frontend:
    build: ./frontend
    ports:
      - '80:80'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
